### ISSUE TITLE
Publish devnet-rs as a crate

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#142]
Also, include this step in the CI/CD
EDIT: also address the TODO in https://github.com/0xSpaceShard/starknet-devnet-rs/blob/64c425b832b96ba09b49646fe0fbf49862c0fb6d/docker/create_joint_image_manifest.sh#L10-L11

**Comment by taco-paco** [comment]
It feels like we need to supply `starknet-server` & `starknet` creates. But supplying `starknet` without `types` crate doesn't really makes sense but at the same time I think supplying `types` create separately doesn't really make sense either since it is only used to make `starknet` crate compile and work which is imo incorrect. @marioiordanov once migration of models to types crate is over I would propose moving types to `starknet` crate
