### ISSUE TITLE
Memory exhaustion 

### ISSUE THREAD

**Issue by sgc-code** [0xSpaceShard/starknet-devnet-rs#272]
**Describe the bug (observed vs expected behavior)**

We completed our migration from devnet python to devnet rust, after a few adjustments now we have all tests running again. There is only one issue. Our tests take around 20 min to run, during that time the devnet memory keeps increasing, after 5 minutes it reaches 7.99Gb and it starts to slow down, after another minute the container stops (no specific error i could find)

As a workaround we are calling the `restart` endpoint every 2 minutes, and that seems to help, although i still see the memory increasing it’s good enough for our test suite (edited)

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Keep using devnet rust for 20 minutes

**Devnet version**

- I am using Devnet version: shardlabs/starknet-devnet-rs:64c425b832b96ba09b49646fe0fbf49862c0fb6d
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: MacOS and also running Github actions on ubuntu

**Comment by FabijanC** [comment]
@mikiw I think you might be after something with that last idea:
![image](https://github.com/0xSpaceShard/starknet-devnet-rs/assets/28579396/fc76500b-7586-4d7e-8d2a-a01f8f625393)

**Comment by FabijanC** [comment]
While minding my own business, I was digging through the code and had some ideas about this issue.
  - I saw that we clone the state in several places (look for `state.clone()`)
    - Those are refactoring candidates, maybe something is not properly dropped due to our use of `Arc`
  - if visual analysis tools weren't of help, there are Rust APIs that return resource usage information
   - Could be used for inserting function calls as sort of breakpoints inside the code
   - Thus we could check where exactly memory grows most
  - Do we know since when this has been a problem?
    - If we can have a simple enough testing procedure (e.g. `N` requests which eventually cause the memory to grow; `N` being sufficiently large), we could reuse it while backtracting revisions to potentially find one without these issues

**Comment by FabijanC** [comment]
@sgc-code hey, do you need old state history? Like, being able to query old states with an old block_id?

**Comment by sgc-code** [comment]
> @sgc-code hey, do you need old state history? Like, being able to query old states with an old block_id?

Hi, @FabijanC if we have a flag to disable old history it could workaround our issue for now. We don't currently need to access the older blocks. Maybe you want to look into some more efficient storage options later. Thanks

**Comment by FabijanC** [comment]
@sgc-code Sure we are also considering more efficient storage options, but were just considering conditional disabling of state storing as the quickest fix.

Thanks for the reply

**Comment by mikiw** [comment]
@sgc-code https://github.com/0xSpaceShard/starknet-devnet-rs/pull/290 was merged so now memory should not growing insanely

**Comment by FabijanC** [comment]
I suspect the largest part of the state history are contract classes. As has already been mentioned somewhere, storing a clone of state (together with declared classes) for each block is highly inefficient. That's why we are currently defaulting to not storing the state history.

## Proposal
Instead of cloning all of the classes, we could have one global storage of type `HashMap<ClassHash, (ContractClass, BlockNumber)>` (wrapped in e.g. `Arc<Mutex<...>>` or `Arc<RwLock<...>>`) - meaning we could store the class together with the block number when it was added.

### Why
So cloning a state would only clone the reference (`Arc`) to the contract class map.

### Implementation details
When retrieving a class (in the response of the JSON-RPC method `starknet_getClass`), we would return the class only if `stored_block_number <= query_block_number`.

Refactoring might be needed to store a contract class together with the next block number, because currently we store the class before the next block is created.

**Comment by FabijanC** [comment]
Similar issue reported on Discord: https://discord.com/channels/793094838509764618/1245283649356566620
