### ISSUE TITLE
Integration tests refactor

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#400]
Remove assertion on transaction_hash in integration tests, because with each new blockifier version the cost of a transaction is changed. This affects the transaction hash. Instead check if the transaction is successful

**Comment by FabijanC** [comment]
This was a question raised back in the days of Devnet-py.

## Pros of asserting transaction hash
- Hash only expected to change in case of certain changes (like blockifier update)
- If the hash value assertion in a test unxpectedly fails, it means there was a change in the code which affected the transaction hash calculation and something needs to be fixed in the code (not in the tests)

## Cons
- Tedious changes in case of blockifier updates or other updates which affect transaction hash
