### ISSUE TITLE
MessagingContract needs to be reloaded after loading from a dump

### ISSUE THREAD

**Issue by pscott** [0xSpaceShard/starknet-devnet-rs#605]
I am currently trying to setup my testing environment once (by deploying a lot of contracts), and then dumping the devnet state.
For each test, I'm reseting the devnet and loading the previously dumped state. This is working fine.

However, I've noticed that even if I've loaded the L1MessagingContract during my setup, I still need to call `.loadL1MessagingContract` after each reset and load.

It would be nice to have this "dumped" as well, to avoid having to load it on each test.

PS: the same behavior happens on connected contracts. e.g if I connect to a contract `foo` during setup, I need to call `foo.connect(myAccount)` at the beginning of each test as it is not part of the "dumped" info.

**Comment by FabijanC** [comment]
Are you using Devnet v0.2.0-rc.3? In other recently reported issues as well?

**Comment by FabijanC** [comment]
Loading of messaging contract is not dumped intentionally. We thought that L1-side actions would make more sense left to the user. But since you are one of the few (if not the only) user combining L1-L2 communication and dumping/loading, messaging-loading could be added to dumpable actions.

## Notes:
- If you don't specify a contract address in your messaging-loading request, it will simply dump the L1 url for future loading. So on next Devnet startup, when the dump is loaded, it will deploy  new messaging contract.
- Flushing is also not dumpable. It produces L2 messaging events which are dumpable though, so the L2 actions resulting from L1-L2 communication indeed get dumped.
- It would probably make sense to mention these things in the docs.

**Comment by FabijanC** [comment]
Feel free to review this PR which aims to close your issue: https://github.com/0xSpaceShard/starknet-devnet-rs/pull/606
